version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sj_foundation
      MYSQL_USER: sj_foundation
      MYSQL_PASSWORD: sj_foundation
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "../WordPress:/var/www/html"
    ports:
      - "8008:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: sj_foundation
      WORDPRESS_DB_PASSWORD: sj_foundation
      WORDPRESS_DB_NAME: sj_foundation
  node:
    build: ../sj_foundation_api/
    volumes:
      - "../sj_foundation_api:/usr/src/app"
    ports:
      - "3010:3010"
    depends_on:
      - db