
// SEARCH ACTIONS
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

// AUTH ACTIONS
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_USER = 'AUTH_SET_USER';

//PROJECT ACTIONS
export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FAILURE = 'PROJECT_FAILURE';
export const PROJECT_META_REQUEST = 'PROJECT_META_REQUEST';
export const PROJECT_META_SUCCESS = 'PROJECT_META_SUCCESS';
export const PROJECT_META_FAILURE = 'PROJECT_META_FAILURE';

export const PLEDGE_REQUEST = 'PLEDGE_REQUEST';
export const PLEDGE_SUCCESS = 'PLEDGE_SUCCESS';
export const PLEDGE_FAILURE = 'PLEDGE_FAILURE';
