
// CREATE PROJECT FORM ACTIONS
export const NEXT_FORM_TAB = 'NEXT_FORM_TAB';

// PROJECT LIST ACTIONS
export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE';
export const PROJECTS_LOAD_MORE = 'PROJECTS_LOAD_MORE';
export const PROJECTS_INIT = 'PROJECTS_INIT';
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';

// COMMENTS ACTIONS
export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';
export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST';
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS';
export const COMMENT_POST_FAILURE = 'COMMENT_POST_FAILURE';

// UPDATE ACTIONS
export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'UPDATE_FAILURE';
export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';

// AUTH ACTIONS
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_USER = 'AUTH_SET_USER';

// USER DETAILS
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_BALANCE_REQUEST = 'USER_BALANCE_REQUEST';
export const USER_BALANCE_SUCCESS = 'USER_BALANCE_SUCCESS';
export const USER_BALANCE_FAILURE = 'USER_BALANCE_FAILURE';
export const TRANSACTIONS_REQUEST = 'TRANSACTIONS_REQUEST';
export const TRANSACTIONS_SUCCESS = 'TRANSACTIONS_SUCCESS';
export const TRANSACTIONS_FAILURE = 'TRANSACTIONS_FAILURE';

// PROJECT ACTIONS
export const PROJECT_INIT = 'PROJECT_INIT';
export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FAILURE = 'PROJECT_FAILURE';
export const PROJECT_PREVIEW_REQUEST = 'PROJECT_PREVIEW_REQUEST';
export const PROJECT_PREVIEW_SUCCESS = 'PROJECT_PREVIEW_SUCCESS';
export const PROJECT_PREVIEW_FAILURE = 'PROJECT_PREVIEW_FAILURE';
export const PROJECT_META_REQUEST = 'PROJECT_META_REQUEST';
export const PROJECT_META_SUCCESS = 'PROJECT_META_SUCCESS';
export const PROJECT_META_FAILURE = 'PROJECT_META_FAILURE';
export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

export const PLEDGE_REQUEST = 'PLEDGE_REQUEST';
export const PLEDGE_SUCCESS = 'PLEDGE_SUCCESS';
export const PLEDGE_FAILURE = 'PLEDGE_FAILURE';
export const SHOW_PLEDGE_MODAL = 'SHOW_PLEDGE_MODAL';

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAILURE = 'WITHDRAW_FAILURE';

// WP PAGES
export const HOWITWORKS_PAGE_REQUEST = 'HOWITWORKS_PAGE_REQUEST';
export const HOWITWORKS_PAGE_SUCCESS = 'HOWITWORKS_PAGE_SUCCESS';
export const HOWITWORKS_PAGE_FAILURE = 'HOWITWORKS_PAGE_FAILURE';

// MODAL
export const MODAL_TOGGLE = 'MODAL_TOGGLE';
